# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.3.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mcc
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
          securityContext:
            fsGroup: 2000
          imagePullSecrets:
            - name: mcc-registry
          # sysctls:
          # - name: net.ipv4.tcp_max_tw_buckets
          #   value: '1440000'
          # - name: net.ipv4.ip_local_port_range
          #   value: '8193 65000'
          # - name: net.core.somaxconn
          #   value: '1024'
        containers:
          main:
            image:
              repository: msconnectedcacheprod.azurecr.io/mcc/linux/iot/mcc-ubuntu-iot-amd64
              tag: 1.2.1.1563
            env:
              IS_SUMMARY_PUBLIC: "true"
              IS_SUMMARY_ACCESS_UNRESTRICTED: "true"
              X_CID: "10000"
              STORAGE_1_SIZE_GB: "10"
            envFrom:
              - secretRef:
                  name: mcc-env
            resources:
              requests:
                # can take 8 hours to stabilise after startup
                cpu: 100m # starts at 250
                memory: 600Mi # starts at 150
              limits:
                # cpu: 400m
                memory: 1Gi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      # healthchecks fail without http path
      main:
        controller: main
        type: LoadBalancer
        # annotations:
        #   external-mdns.blakecovarrubias.com/hostnames: example._microsoft_mcc._tcp
        #   external-mdns.blakecovarrubias.com/without-namespace: "true"
        ports:
          http:
            port: 80
            targetPort: 8081
      metrics:
        primary: true
        controller: main
        ports:
          metrics:
            port: 5000
    persistence:
      shared:
        type: emptyDir
        sizeLimit: 10Gi
        globalMounts:
          - path: /nginx/cache1
