apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: s4dfarm-cnpg
  namespace: default
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: longhorn-skipbackup
  imageName: ghcr.io/cloudnative-pg/postgresql:14

  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore:
  #     endpointURL: https://s3.us-west-004.backblazeb2.com
  #     destinationPath: s3://tplant-homelab-postgres
  #     s3Credentials:
  #       accessKeyId:
  #         name: cloudnative-pg
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: cloudnative-pg
  #         key: ACCESS_SECRET_KEY
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip

  bootstrap:
    recovery:
      source: s4dfarm-cnpg

  externalClusters:
    - name: s4dfarm-cnpg
      barmanObjectStore:
        endpointURL: https://s3.us-west-004.backblazeb2.com
        destinationPath: s3://tplant-homelab-postgres
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: cloudnative-pg
            key: ACCESS_SECRET_KEY

  # otherwise postgres crashes with hugepages enabled
  resources:
    requests:
      memory: 100Mi
      hugepages-2Mi: 100Mi
    limits:
      memory: 1Gi
      hugepages-2Mi: 100Mi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: s4dfarm
  namespace: default
spec:
  immediate: true
  schedule: 0 0 0 * * *
  backupOwnerReference: self
  cluster:
    name: s4dfarm-cnpg
